# Generated by Django 5.1.6 on 2025-03-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=45, unique=True)),
                ('cnpj_cpf', models.CharField(max_length=18, unique=True)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
    ]
